id = "cypher"
name = "OpenCypher"
version = "0.1.0"
description = "Provides syntax highlighting and language server support for Cypher."
authors = ["Torsten Boettjer"]
repository = "https://github.com/torstenboettjer/cypher"
schema_version = 1

[grammars.cypher]
repository = "https://github.com/taekwombo/tree-sitter-cypher"
commit = "737b75c828821964a178ab22d83136dd42fd91d1"
